[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://lovable.dev/projects/2c5cc1d1-998c-4fbd-8f92-d7bc54df746c"
additional_redirect_urls = ["https://lovable.dev/projects/2c5cc1d1-998c-4fbd-8f92-d7bc54df746c", "http://localhost:3000", "https://localhost:3000"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[functions.ai-inventory-assistant]
verify_jwt = true
