// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkosolisgvvukreooren.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rb3NvbGlzZ3Z2dWtyZW9vcmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NzM3MTAsImV4cCI6MjA2NjE0OTcxMH0.A3ex8ZrtLxj76Ndv4qECrViGDWY00L7q5fh8Koh53Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);